name: deploy_test

on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: [ ubuntu-latest ]
        env:
            working-directory: ./frontend
        
        strategy:
            matrix:
                node-version: [ 16.x ]
        
        steps:
            # 브랜치 체크아웃
            -   name: checkout main branch
                uses: actions/checkout@v2
            
            # Node.js 환경설정
            -   name: use node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            
            # npm caching
            -   name: cache node modules
                uses: actions/cache@v2
                id: cache
                with:
                    path: node_modules
                    key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
            
            -   name: install packages
                if: steps.cache.outputs.cache-hit != 'true'
                run: npm install
                working-directory: ${{ env.working-directory }}

            -   name: build
                run: npm run build
                working-directory: ${{ env.working-directory }}

            -   name: SSHPASS Github Action
                uses: matheusvanzan/sshpass-action@v2
                with: 
                    host: ${{ secrets.SERVER_HOST }}
                    port: ${{ secrets.SERVER_PORT }}
                    user: ${{ secrets.SERVER_USER }}
                    pass: ${{ secrets.SERVER_PASS }}
                    run: |
                        scp -P ${{ secrets.SERVER_PORT }} -r ./frontend/build ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home